### ISSUE TITLE
No multiplayer save

### ISSUE THREAD

**Issue by lolmanupro** [flarfo/Muck-SaveUtility#1]
yeah so i was playing with my friend just recently, and when i saved and later joined the game together with him he didnt have his power ups, we put his items in a chest which was alright but he had no power ups and got very weak, too weak and got overwhelmed by the mobs. This made it impossible to use the mod as a viable solution to play regularly the game because we werent able to continue our save file after rejoining the world. Anyways the mod is really good for playing by yourself and you can get the most out of the game using the mod, but i think Muck is much better with friends hence it would be appreciated if there was multiplayer support. Thanks

**Comment by lolmanupro** [comment]
Didnt mention how chests and statues just come back when rejoining the world via the save file and that all power ups will double or stack to 2

**Comment by flarfo** [comment]
multiplayer wasn't supported prior to release 0.3.0, if you download the newest release (https://muck.thunderstore.io/package/flarfo/SaveUtility/) everything should work!
