### ISSUE TITLE
Player.steamId not found

### ISSUE THREAD

**Issue by ghost** [flarfo/Muck-SaveUtility#3]
Hi, I managed to get the plugin running on my linux machine, but the loading & saving does not seem to be working. After a bit of digging I found this:

```
[Info   : Unity Log] HAS SAVE LOADED
[Info   : Unity Log] Loading
[Info   : Unity Log] SAVE LOADED -328723458.muck
[Info   : Unity Log] CUSTOM SAVES
[Info   : Unity Log] CUSTOM SAVES LOADED
[Error  : Unity Log] MissingFieldException: Field 'Player.steamId' not found.
Stack trace:
SaveUtility.ServerMethods.SendHasSave () (at <f81dec9e936e45f2b10374527df7506a>:0)
SaveUtility.LoadManager.LoadOnStart () (at <f81dec9e936e45f2b10374527df7506a>:0)
MenuUI.StartGame () (at <67f488ac102f478da1b726e8e3339fbe>:0)
UnityEngine.Events.InvokableCall.Invoke () (at <4e31edee49244f41a8451ffc4c7327c1>:0)
UnityEngine.Events.UnityEvent.Invoke () (at <4e31edee49244f41a8451ffc4c7327c1>:0)
UnityEngine.UI.Button.Press () (at <90ccf370126f4853bf5480dfc3719aeb>:0)
UnityEngine.UI.Button.OnPointerClick (UnityEngine.EventSystems.PointerEventData eventData) (at <90ccf370126f4853bf5480dfc3719aeb>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute (UnityEngine.EventSystems.IPointerClickHandler handler, UnityEngine.EventSystems.BaseEventData eventData) (at <90ccf370126f4853bf5480dfc3719aeb>:0)
UnityEngine.EventSystems.ExecuteEvents.Execute[T] (UnityEngine.GameObject target, UnityEngine.EventSystems.BaseEventData eventData, UnityEngine.EventSystems.ExecuteEvents+EventFunction`1[T1] functor) (at <90ccf370126f4853bf5480dfc3719aeb>:0)
UnityEngine.EventSystems.EventSystem:Update()

[Info   : Unity Log] Lobby left successfully
```

At first I thought the plugin was not working due to missing path Program Files (x86)\Steam\steamapps\common\Muck\Muck_Data\Managed\Assembly-CSharp.dll but that would not seem to be the case. My friend sent me a save himself (since I could not save), but I managed to see the save show up in the menus correctly.

**Comment by sodiboo** [comment]
Install [UnifiedSteamworks](https://muck.thunderstore.io/package/Terrain/UnifiedSteamworks/)

SaveUtility is built against the windows version of Facepunch.Steamworks, and UnifiedSteamworks is a compatibility layer that allows those references to work on the POSIX version

**Comment by ghost** [comment]
Thanks @Terrain2, works like a charm!

**Comment by Ibrahim-Rashwan** [comment]
> Install [UnifiedSteamworks](https://muck.thunderstore.io/package/Terrain/UnifiedSteamworks/)
> 
> SaveUtility is built against the windows version of Facepunch.Steamworks, and UnifiedSteamworks is a compatibility layer that allows those references to work on the POSIX version

Thanks Very Much i started to lose hope this comment really saved me, Thanks again. **VERY_COOL**
