### ISSUE TITLE
Empty inventory and 0 HP

### ISSUE THREAD

**Issue by Tekurm** [flarfo/Muck-SaveUtility#3]
After a while I died, quit, loaded the save and spawned with 0 HP (but still not dead) and an empty inventory

**Comment by flarfo** [comment]
saving your world after your death would result in you spawning in with 0 HP after loading the save. with release 0.3.0 (https://muck.thunderstore.io/package/flarfo/SaveUtility/) this issue is fixed. all items dropped on the ground will be saved as well.
